name: Deploying Tutorial React App

on:
  push:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: surge ./bootcampclass3-anwar.surge.sh --token ${{ secrets.SURGE_TOKEN2 }}
